// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDang2SHfeC2DAF2-QTDat51p0UHQ_e-H8',
    appId: '1:820535541122:web:4e96527bdad33ba72d239b',
    messagingSenderId: '820535541122',
    projectId: 'digitalcardyard',
    authDomain: 'digitalcardyard.firebaseapp.com',
    storageBucket: 'digitalcardyard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDztn9P54-6RVP5_XhovOX-OB2oskLb5yQ',
    appId: '1:820535541122:android:b8feea433798441f2d239b',
    messagingSenderId: '820535541122',
    projectId: 'digitalcardyard',
    storageBucket: 'digitalcardyard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKNs8Dq1WqrfeZln7VYtdV6v9IE66IA4',
    appId: '1:820535541122:ios:b1362efebeafbd1f2d239b',
    messagingSenderId: '820535541122',
    projectId: 'digitalcardyard',
    storageBucket: 'digitalcardyard.appspot.com',
    iosBundleId: 'com.example.digitalcaryard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKNs8Dq1WqrfeZln7VYtdV6v9IE66IA4',
    appId: '1:820535541122:ios:b1362efebeafbd1f2d239b',
    messagingSenderId: '820535541122',
    projectId: 'digitalcardyard',
    storageBucket: 'digitalcardyard.appspot.com',
    iosBundleId: 'com.example.digitalcaryard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDang2SHfeC2DAF2-QTDat51p0UHQ_e-H8',
    appId: '1:820535541122:web:a323c01a973503ce2d239b',
    messagingSenderId: '820535541122',
    projectId: 'digitalcardyard',
    authDomain: 'digitalcardyard.firebaseapp.com',
    storageBucket: 'digitalcardyard.appspot.com',
  );
}
